"""empty message

Revision ID: 042613da95c8
Revises: add_corrected_keypoints
Create Date: 2026-01-16 13:13:41.114221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042613da95c8'
down_revision = 'add_corrected_keypoints'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrected_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_image_path', sa.String(length=255), nullable=False),
    sa.Column('corrected_result_path', sa.String(length=255), nullable=True),
    sa.Column('keypoints_json', sa.Text(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['keypoint_detections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corrected_images')
    # ### end Alembic commands ###
