"""Initial migration

Revision ID: 405d0aa670d6
Revises: 
Create Date: 2025-10-08 11:50:56.019285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405d0aa670d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('keypoint_detections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('result_path', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('prediction_result', sa.String(length=50), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('segmentation_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('x_coord', sa.Float(), nullable=False),
    sa.Column('y_coord', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['keypoint_detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keypoints')
    op.drop_table('keypoint_detections')
    op.drop_table('users')
    # ### end Alembic commands ###
