"""add_corrected_keypoints_table

Revision ID: add_corrected_keypoints
Revises: 405d0aa670d6
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'add_corrected_keypoints'
down_revision = '405d0aa670d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrected_keypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('x_coord', sa.Float(), nullable=False),
    sa.Column('y_coord', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('original_x', sa.Float(), nullable=True),
    sa.Column('original_y', sa.Float(), nullable=True),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['keypoint_detections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corrected_keypoints')
    # ### end Alembic commands ###
